#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2022, Not a Team.
#
# Distributed under the terms of the MIT License License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qp_test_plugin import plugin


@click.command()
@click.option('--env-script', prompt='Environment script',
              default='source activate qp-test-plugin')
@click.option('--server-cert', prompt='Server certificate', default='None')
def config(env_script, server_cert):
    """Generates the Qiita configuration files"""
    if server_cert == 'None':
        server_cert = None
    plugin.generate_config(env_script, 'start_qp_test_plugin', server_cert=server_cert)

if __name__ == '__main__':
    config()
